### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by amamadman** [Ciarands/vidsrc-me-resolver#4]
How did you get the decode_hls_url function?
I'm trying make the decode function for https://embed.smashystream.com/pl3.js?v=0.13
Can you please explain how to make that?

Here's an example string
#2aHR0cHM6Ly9rLnBvbGxsbG9wLmNvbS9fdjExLzgxYjE2ZDhmZjI5NTZkM2JlMDQ2NzI5MTIxZGYyMzUwYzJm//U0ZML2RVN0IvRGx4YzEyNjUzZTY4ODU3ZTJkNWMxODU3MmFmZGNhMmIwZWUwN2JjYWZiMWViOTBkNTUyMzBmM//eE52L1QwOC96N0YzTY0NjkxMTgwZWNmOTBlMmUyNWU4YWY0MGUxYjUzNDM4ZjIyZTA2NjI2NzQyZTFkODA2ZjVjMjgzZjgyMDY1MTU4MjNlOWU0NDRiYTlhZGVlZmY4OTYxYjY3MGU5OWQ5NTAwNzNhOTM3ZTBjYzc3ZDg1OWU4MTI0NTgxYmI5ZmMzNjlmNDNkNjI5YWRmMzZiMW//SGJ0L1dGakIvN0dXZiYjVlMDBmZjZkMzU0Mjc5MzA//MGNhL0JWb0kvTlM54NmM3YW//Ym94LzJTSS9aU0ZjNkNDkwOGYzNjZhNmNjNjJjY2YyZjk4ZTliYTI1MGI5Mi9wbGF5bGlzdC5tM3U4

**Comment by Ciarands** [comment]
Join the discord in the readme, theres a writeup there on how to decrypt playerjs strings
